const jsonData = [
  {
    id: 1,
    name: "John Doe",
    date: "2024-02-08",
    address: "123 Main St, City, Country",
    course: "Sql",
    coupon: "W15",
  },
  {
    id: 2,
    name: "Jane Smith",
    date: "2024-02-10",
    address: "456 Elm St, Town, Country",
    course: "Python",
    coupon: "SF-24",
  },
  {
    id: 3,
    name: "Alice Johnson",
    date: "2024-02-12",
    address: "789 Oak St, Village, Country",
    course: "Python",
    coupon: "W15",
  },
  {
    id: 4,
    name: "Bob Williams",
    date: "2024-02-15",
    address: "101 Pine St, Hamlet, Country",
    course: "Sql",
    coupon: "SF-24",
  },
  {
    id: 5,
    name: "Eva Brown",
    date: "2024-02-18",
    address: "246 Maple St, Suburb, Country",
    course: "Ruby",
    coupon: "W15",
  },
  {
    id: 6,
    name: "Michael Lee",
    date: "2024-02-20",
    address: "369 Cedar St, Rural, Country",
    course: "Ruby",
    coupon: "MCL38",
  },
  {
    id: 7,
    name: "Sophia Garcia",
    date: "2024-02-22",
    address: "808 Birch St, Countryside, Country",
    course: "React",
    coupon: "RB20",
  },
  {
    id: 8,
    name: "David Martinez",
    date: "2024-02-24",
    address: "555 Walnut St, County, Country",
    course: "React",
    coupon: "MCL38",
  },
  {
    id: 9,
    name: "Olivia Rodriguez",
    date: "2024-02-26",
    address: "777 Oak St, Valley, Country",
    course: "HTML",
    coupon: "RB20",
  },
  {
    id: 10,
    name: "William Taylor",
    date: "2024-02-28",
    address: "888 Pine St, Mountains, Country",
    course: "HTML",
    coupon: "MCL38",
  },
];